import Head from 'next/head';
import About from '../components/about';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Protest Tunes | General Strike</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1>Protest Tunes</h1>
			<About />
		</div>
	);
}
